### PR TITLE
Added Eagle CAM 8.6+

### PR DESCRIPTION
**Pull request by Pnoxi**
It still needs to be tested.
For example, there is no duplicate layer Dimension(21)/Board Shape and Milling(46)/Cutouts for production.
Or you do not have a problem with the "Gerber X2", I can switch to "Gerber RS-274X".

You could help with this, gerber data looked correctly on your site (image view).

Here is a comparison of the generated CAM-7.2 vs CAM-8.6 images (included 2 layers and 4 layers PCB)
https://drive.google.com/file/d/1i22MNQ05ag8PGntIfpS7PBE4eGG9tHII/view?usp=sharing

### CODE REVIEW

**Comment by tekdemo** [comment]
Thanks for giving this a go! We might pull this later and/or make tweaks, but currently Autodesk has me worried about using their JSON format, due to a nasty glitch in Eagle 9.2.0 that broke Eagle JSON cam jobs. This involved adding new format options with a problematic default, effectively requiring an updated JSON file to fix it and undo the new option and default. The "legacy" cam jobs work really robustly, which we tend to prefer in general. We'll be considering use of the JSON format once it feels less likely to be modified in a few versions.

Additionally, we actually have an CAM built into Eagle already. If you go to Load CAM Job > Third Party > OSHPark, you'll see it. Since this is already distributed to everyone, it's a bit redundant to include it here, although that doesn't include the easy update method.

**Comment by Pnoxi** [comment]
It is a pity :D

I know the eagle contains the "CAM Job > Third Party > OSHPark". But that is not usable!
On some PCBs I use the complicated outline (dxf import), and the eagle does not work them correctly. It does not export them to gerber data.
So exporting Layer 21(Dimension) is better than Board Shape.
The second problem is that it does not export the 46(Milling) layer. And the user will not notice it.
My CAM has fixed it

The "legacy" CAM for me again they are not usable. I have a lot of polygons on PCB.
I will get a timeout error when uploading eagle brd to your site.
So I must generate Gerber data, with Legacy format it takes about 10 minutes on my intel i5. With a new format it takes a few seconds.
Also, the size is significantly lower (legacy zip: 5.8MB, new format zip: 255kB).

**Comment by tekdemo** [comment]
Are you using zero width polygons? That's the only thing we've seen that
makes the legacy cam choke. Zero width polygons actually affects thermals
and the DRC check, so it's not recommended to use that polygon width. It's
very easy to have flawed or missing connections when you set the width too
low.  Setting it higher resolves that, as well as fixing the cam processing
time.

The DXF issue is likely rounding, as eagle uses incredibly precise
coordinates internally, and DXF can have rounding issues that prevents
proper line connections. This means the cam outline detection can fail, as
it's broken into multiple segments. DXF in general has lots of import
issues in general, due to information loss in that format.

Hit us up at support if you need help with anything.

**Comment by Pnoxi** [comment]
Yes, I'm using zero width polygons.
Accuracy is my priority! Yes, I can play with it, shrink the polygon so it looks similar. But why? I want to have things the way I drew them. I have control, for example, on insulating gaps.
I have, for example, a library with a logos, of different sizes, I can not imagine reworking it (more than 1000).

Here is a micro USB footprint. Solder Paste (gray) is a zero width polygon. Pad to the left 0.127 and right 0.254.
https://drive.google.com/file/d/1uImmWhjXWpGZ1AytUBHVzTqOZuaqM1EE/view?usp=sharing

Here is my logo:
zero width polygon
https://drive.google.com/file/d/1tNvnKvST5I-kaEbCmvBONTyWwwRxyCUm/view?usp=sharing
0.127 width polygon
https://drive.google.com/file/d/16u7dzgb8XdI7Sl_Ywwp-fY5Z2pkkGXPz/view?usp=sharing
0.254 width polygon
https://drive.google.com/file/d/15prjVqJ5wdCwfU2nJNYBK93IS21PBWRO/view?usp=sharing

I will continue to use zero width polygons because it is more comfortable, faster for me...

As for dxf, I have to use autocad. I can not imagine drawing something in eagle. It's terrible...
Dimension example, the eagle did not detect him, so it is better to use the export layer 21
https://drive.google.com/file/d/1DyQMjb2pYn4CH8JXTUbHA7rOf96MEbiO/view?usp=sharing

I will close it, it is now useful for me to use my new CAM files :)

**Pull request closed without merging**
